version: '3.3'
services:
  gitlab-ce:
    image: 'gitlab/gitlab-ce:15.10.8-ce.0'
    restart: always
    container_name: 'gitlab'
    ports:
      - '2022:22'
      - '80:80'
      - '443:443'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - './ssl:/etc/gitlab/ssl'
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "1"
